version: '3'

services:
  postgres:
    image: duckluckmarket/postgres:${TAG}
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./configs/init_auth_db.sql:/docker-entrypoint-initdb.d/init_auth_db.sql
    networks:
      - app-network
  redis:
    image: redis
    restart: unless-stopped
    networks:
      - app-network
  server:
    depends_on:
      - postgres
    image: duckluckmarket/godeploy:${TAG}
    container_name: api_server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./log:/log
      - ./configs/envs:/configs/envs
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
