global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'golang'
    static_configs:
      - targets: ['api-server:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']