name: Build and deploy

env:
  TAG: v1.7

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker api-server image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/api-server:${{ env.TAG }} --target api-server .
      - name: Push the api_server image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/api-server:${{ env.TAG }}
      - name: Build Docker api-db image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/api-db:${{ env.TAG }} --target api-db .
      - name: Push the api-db image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/api-db:${{ env.TAG }}
      - name: Build Docker session-service image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/session-service:${{ env.TAG }} --target session-service .
      - name: Push the session-service image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/session-service:${{ env.TAG }}
      - name: Build Docker cart-service image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/cart-service:${{ env.TAG }} --target cart-service .
      - name: Push the cart-service image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/cart-service:${{ env.TAG }}
      - name: Build Docker auth-service image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/auth-service:${{ env.TAG }} --target auth-service .
      - name: Push the auth-service image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godeploy/auth-service:${{ env.TAG }}
      - name: Upload dependencies
        uses: actions/upload-artifact@v2
        with:
          name: Backend
          path: |
            ./docker-compose.yml
            ./log
            ./configs/init.sql
            ./uploads
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dependencies
        uses: actions/download-artifact@v1
        with:
          name: Backend
      - name: Transfer dependencies to api_server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "Backend"
          target: "/home/ubuntu/duckluckmarket"

      - name: pull api_server docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/godeploy:${{ env.TAG }}
      - name: pull postgres docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/postgres:${{ env.TAG }}
      - name: deploy docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/duckluckmarket/Backend
            echo TAG=${{ env.TAG }} > .env
            sudo docker-compose rm -fsv postgres
            sudo docker-compose rm -fsv server
            sudo docker-compose up -d