name: Build and deploy

env:
  API_DB_TAG: v1.7
  API_SERVER_TAG: v1.7
  SESSION_SERVICE_TAG: v1.7
  AUTH_SERVICE_TAG: v1.7
  CART_SERVICE_TAG: v1.7

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Hello**
            🌏
            !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false # This is the default
#
#on:
#  push:
#    branches: [ develop, main ]
#  pull_request:
#    branches: [ develop, main ]
#
#jobs:
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        if: success()
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.15.x
#      - uses: actions/checkout@v1
#      - name: Get full coverage
#        run: go test -coverprofile=coverage1.out -coverpkg=./... -cover ./...
#      - name: Ignore some directories
#        run: cat coverage1.out | grep -v mock | grep -v proto | grep -v cmd | grep -v middleware | grep -v models > cover.out
#      - name: Get total coverage
#        run: go tool cover -func cover.out
#      - name: Convert coverage to lcov
#        uses: jandelgado/gcov2lcov-action@v1.0.5
#        with:
#          infile: cover.out
#          outfile: cover.lcov
#      - name: Upload badge to hotbox
#        uses: jakejarvis/s3-sync-action@master
#        with:
#          args: --endpoint-url https://hb.bizmrg.com --acl public-read --follow-symlinks
#        env:
#          AWS_S3_BUCKET: ${{ secrets.DUCKLUCK_COVERAGE_BUCKET }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.DUCKLUCK_COVERAGE_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.DUCKLUCK_COVERAGE_SECRET }}
#          SOURCE_DIR: 'cover.lcov'
