name: Docker Build

on:
  push:
    branches: [ deploy_test ]
  pull_request:
    branches: [ deploy_test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/godeploy:${GITHUB_SHA::8} .
      - name: Push the image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godeploy:${GITHUB_SHA::8}
      - name: Upload dependencies
        uses: actions/upload-artifact@v2
        with:
          name: Backend
          path: |
            ./docker-compose.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dependencies
        uses: actions/download-artifact@v1
        with:
          name: Backend
      - name: Transfer dependencies to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "Backend"
          target: "/home/ubuntu/duckluckmarket"

      - name: pull docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/godeploy:${GITHUB_SHA::8}
      - name: deploy docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker rm -f $(sudo docker ps -aq)
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/godeploy:${GITHUB_SHA::8}