name: Build and deploy

env:
  TAG: v1.4

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker server image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/godeploy:${{ env.TAG }} --target server .
      - name: Push the server image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/godeploy:${{ env.TAG }}
      - name: Build Docker postgres image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/postgres:${{ env.TAG }} --target postgres .
      - name: Push the postgres image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres:${{ env.TAG }}
      - name: Upload dependencies
        uses: actions/upload-artifact@v2
        with:
          name: Backend
          path: |
            ./docker-compose.yml
            ./log
            ./configs/init.sql
            ./uploads
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dependencies
        uses: actions/download-artifact@v1
        with:
          name: Backend
      - name: Transfer dependencies to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "Backend"
          target: "/home/ubuntu/duckluckmarket"

      - name: pull server docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/godeploy:${{ env.TAG }}
      - name: pull postgres docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/postgres:${{ env.TAG }}
      - name: deploy docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/duckluckmarket/Backend
            echo TAG=${{ env.TAG }} > .env
            sudo docker-compose up -d